"""
Django settings for SINTER project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2rp&310kt4&hjkjgy$gf2kk-td1-0ao9@_3*vq^*pwt*+5nwih'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SINTER.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SINTER.wsgi.application'

# Cache in-memory (melhora performance de sessões e dados voláteis)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'sinter-cache',
        'TIMEOUT': 300,  # 5 minutos
    }
}

# Cache da resposta do agente "Faça sua pergunta"
ASK_CACHE_TIMEOUT = int(os.getenv("ASK_CACHE_TIMEOUT", "900"))

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

CORE_RULES_PATH = BASE_DIR / "documents" / "regras.txt"
RAG_INDEX_PATH = BASE_DIR / "documents" / "faiss_index"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenAI / LangChain
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1')
OPENAI_TEMPERATURE = float(os.getenv('OPENAI_TEMPERATURE', '0'))

# Configurações de chunk/overlap para o RAG
RAG_CHUNK_SIZE = int(os.getenv('RAG_CHUNK_SIZE', '700'))
RAG_CHUNK_OVERLAP = int(os.getenv('RAG_CHUNK_OVERLAP', '150'))

# Caminho para o documento de regras usado pelo RAG.
# Defina CORE_RULES_PATH para um arquivo específico ou coloque arquivos em CORE_RULES_DIR (padrão: BASE_DIR/documents).
RAG_DOCS_DIR = Path(os.getenv('CORE_RULES_DIR', BASE_DIR / 'documents'))
_doc_extensions = {'.pdf', '.txt', '.md'}
_docs_found = sorted([p for p in RAG_DOCS_DIR.glob("*") if p.suffix.lower() in _doc_extensions and p.is_file()])
_default_rules = _docs_found[0] if _docs_found else None
CORE_RULES_PATH = os.getenv('CORE_RULES_PATH') or (str(_default_rules) if _default_rules else None)
RAG_INDEX_PATH = os.getenv('RAG_INDEX_PATH') or str(RAG_DOCS_DIR / 'faiss_index')

# Sessions via cookie para evitar escrita no banco (usuário read-only).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
